class Fixnum
  def tipo_por_extenso
    case self
      when 1 then "Equipamento"
      when 2 then "Equipamento para Aquisição Permanente"
      when 3 then "Mão de Obra"
      when 4 then "Material"
      when 5 then "Serviços"
      when 6 then "Taxas"
      when 7 then "Outros"
      when 8 then "Franquia"
      when 9 then "Administração"
      when 10 then "Aluguel"
      when 11 then "Verba"
      else
        self
    end
  end

  def tipo_de_composicao_orse_por_extenso
    case self
      when 1 then "OBRAS CIVIS"
      when 2 then "INFRA-ESTRUTURA"
      when 3 then "PROJETOS"
      when 4 then "Serviços Preliminares"
      when 5 then "Fundações"
      when 6 then "Estruturas"
      when 7 then "Elevações"
      when 8 then "Coberturas"
      when 9 then "Instalações Elétricas/Telefônicas/Cabeamento Estruturado"
      when 10 then "Instalações Hidráulicas"
      when 11 then "Instalações de Combate a Incêndio"
      when 12 then "Instalações Sanitárias"
      when 13 then "Esquadrias"
      when 14 then "Revestimentos de Tetos e Paredes"
      when 15 then "Louças e Metais"
      when 16 then "Pavimentação"
      when 17 then "Pinturas e Tratamentos"
      when 18 then "Instalação de Antena Coletiva"
      when 19 then "Instalação de Gás de Cozinha"
      when 20 then "Instalação de Ar Condicionado"
      when 21 then "Instalações de Gases Medicinais"
      when 22 then "Instalação de Câmaras Frigoríficas"
      when 23 then "Diversos"
      when 24 then "Serviços Auxiliares de Obras Civis"
      when 25 then "Provisório"
      when 26 then "X - Grupo Provisório de Serviços / Distribuir"
      when 27 then "Terraplenagem"
      when 28 then "Urbanismo e Sinalização"
      when 29 then "Pavimentação Rodoviária"
      when 30 then "Redes de Água e Adutoras"
      when 31 then "Estações de Tratamento e Elevatórias de Água"
      when 32 then "Poços Artesianos"
      when 33 then "Redes de Esgotos"
      when 34 then "Estação de Tratamento e Elevatórias de Esgotos Sanitários"
      when 35 then "Redes de Drenagem"
      when 36 then "Redes de Irrigação"
      when 37 then "Redes de Distribuição de Energia Elétrica  e de Iluminação Pública em Tensão Classe 35 ou"
      when 38 then "Redes de Telefonia"
      when 39 then "Contenções e Escoramentos"
      when 40 then "Esgotamentos de Água"
      when 41 then "Serviços Auxiliares de Infra-estrutura"
      when 42 then "Apoio Administrativo de Obra"
      when 43 then "Projetos Básicos e Executivos"
      when 44 then "Serviços Iniciais de Obras Civis"
      when 45 then "Demolições / Remoções"
      when 46 then "Locação de Edificações"
      when 47 then "Mobilização / Instalações Provisórias / Desmobilização"
      when 48 then "Escavações"
      when 49 then "Aterros / Reaterros / Compactações"
      when 50 then "Formas para Fundações"
      when 51 then "Alvenarias de Pedra e Concretos para Fundações"
      when 52 then "Estacas Brocas"
      when 53 then "Estacas Pré-Moldadas"
      when 54 then "Estacas Moldadas no local Tipo Strauss"
      when 55 then "Estacas Moldadas no local Tipo Franki"
      when 56 then "Estacas Metálicas"
      when 57 then "Tubulões"
      when 58 then "Camadas Reguralizadoras"
      when 59 then "Formas"
      when 60 then "Concreto Simples"
      when 61 then "Concreto Armado"
      when 62 then "Escoramento em Edificações"
      when 63 then "Armaduras Convencionais"
      when 64 then "Fios e Cordoalhas de Protensão"
      when 65 then "Estruturas Pre-Moldadas de Concreto"
      when 66 then "Alvenarias de Vedação"
      when 67 then "Elementos Vazados"
      when 68 then "Divisórias"
      when 69 then "Colunas em Alvenaria"
      when 70 then "Madeiramento"
      when 71 then "Estrutura Metálica"
      when 72 then "Telhamento"
      when 73 then "Complementos"
      when 74 then "Subsestação Transformadora Abrigada"
      when 75 then "Subestação Transformadora em Poste"
      when 76 then "Entrada em Baixa Tensão"
      when 77 then "Interligações até Quadro Geral - Eletrodutos e Conexões"
      when 78 then "Interligações até Quadro Geral - Fios e Cabos"
      when 79 then "Fusíveis, Disjuntores e Chaves"
      when 80 then "Quadros de Distribuição de Energia"
      when 81 then "Quadros de Distribuição de Telefone"
      when 82 then "Luminárias Internas"
      when 83 then "Luminárias Externas"
      when 84 then "Luminárias Industriais"
      when 85 then "Revisões e Reposições"
      when 86 then "Pontos de Suprimento de Energia Convencionais"
      when 87 then "Pontos de Suprimento de Telefone"
      when 88 then "Pontos de Suprimento de Energia para Ar Condicionado"
      when 89 then "Pontos de Suprimento de Energia para Computador"
      when 90 then "Pontos de Suprimento de Lógica"
      when 91 then "Tomadas Convencionais e Interruptores"
      when 92 then "Tomadas para Telefone"
      when 93 then "Tomadas para Ar Condicionado"
      when 94 then "Tomadas para Computadores"
      when 95 then "Tomadas para Lógica"
      when 96 then "Postes Tubulares de Ferro Galvanizado"
      when 97 then "Aparelhos, Utensílios e Equipamentos Elétricos"
      when 98 then "Pára-raios"
      when 99 then "Tubos e Conexões de Ferro Galvanizado"
      when 100 then "Tubos e Conexões de PVC Rígido Soldável"
      when 101 then "Tubos e Conexões de PVC Rígido Roscável"
      when 102 then "Tubos e Conexões de Ferro Fundido"
      when 103 then "Tubos e Conexões de Cobre Soldáveis e Roscáveis"
      when 104 then "Reservatórios"
      when 105 then "Registros e Válvulas"
      when 106 then "Equipamentos para Combate a Incêndio"
      when 107 then "Tubos e Conexões de PVC Rígido Soldável para Esgoto"
      when 108 then "Pontos de Ligação de Esgoto"
      when 109 then "Caixas de Inspeção"
      when 110 then "Fossas Sépticas"
      when 111 then "Fossas Secas"
      when 112 then "Filtros e Sumidouros"
      when 113 then "Esquadrias de Madeira"
      when 114 then "Esquadrias de Alumínio"
      when 115 then "Esquadrias de Ferro"
      when 116 then "Vidros Lisos"
      when 117 then "Vidros Tipo Fantasia"
      when 118 then "Vidros Laminados"
      when 119 then "Vidros Temperados"
      when 120 then "Vidros Aramados"
      when 121 then "Espelhos"
      when 122 then "Persianas e Cortinas"
      when 123 then "Argamassas"
      when 124 then "Azulejos e Cerâmicas"
      when 125 then "Revestimento com Pedras"
      when 126 then "Revestimentos em Laminados"
      when 127 then "Revestimentos com Mármores e Granitos"
      when 128 then "Revestimentos com Papel de Parede"
      when 129 then "Forros"
      when 130 then "Impermeabilização"
      when 131 then "Isolamento Térmico"
      when 132 then "Isolamento Acústico"
      when 133 then "Peitoris e Tampos de Balcões"
      when 134 then "Falhas em Revestimentos"
      when 135 then "Louças e Metais Sanitários"
      when 136 then "Pisos : Cimentados, em Concreto Simples, tipo Tech-Stone e de Alta Resistência"
      when 137 then "Pisos Cerâmicos"
      when 138 then "Pisos com Pedras"
      when 139 then "Pisos Sintéticos / Vinílicos"
      when 140 then "Pisos de Madeira"
      when 141 then "Pisos de Borracha"
      when 142 then "Pavimentações Externas"
      when 143 then "Soleiras e Rodapés"
      when 144 then "Latex PVA"
      when 145 then "Esmalte Sintético / Óleo"
      when 146 then "Pintura em Estrutura Metálica"
      when 147 then "Outras Pinturas"
      when 148 then "Tratamentos de Superfícies"
      when 149 then "Equipamentos e Acessórios para Antena Coletiva"
      when 150 then "Equipamentos e Acessórios para Instalações de Gás de Cozinha"
      when 151 then "Equipamentos e Acessórios para Instalação de Ar Condicionado"
      when 152 then "Fornecimento de Gases Medicinais"
      when 153 then "Redes de Distribuição de Gases"
      when 154 then "Equipamentos e Acessórios para Centrais de Suprimento e Redes de Distribuição de Gases"
      when 155 then "Equipamentos e Acessórios para Postos de Consumo"
      when 156 then "Equipamentos para Câmaras Frigoríficas"
      when 157 then "Portas Frigoríficas"
      when 158 then "Acessórios para Instalação de Câmaras Frigoríficas"
      when 159 then "Muros"
      when 160 then "Cercas"
      when 161 then "Alambrados e Gradis"
      when 162 then "Paisagismo"
      when 163 then "Urbanização de Parques e Praças"
      when 164 then "Limpeza"
      when 165 then "Andaimes"
      when 166 then "Anadimes"
      when 167 then "Mobiliário"
      when 168 then "Diversos"
      when 169 then "Execução de Rasgos em Alvenaria e Concretos para Passagem de Tubulações"
      when 170 then "Enchimento de Rasgos em Alvenaria ou Concreto"
      when 171 then "Transporte de Materiais na Obra"
      when 172 then "Provisórios"
      when 173 then "Grupo Provisório - Distribuir"
      when 174 then "Desmatamento e Limpeza"
      when 175 then "Regularização de Áreas"
      when 176 then "Escavação Manual em Área Urbana"
      when 177 then "Escavação Manual em Campo Aberto"
      when 178 then "Escavação Mecanizada em Área Urbana"
      when 179 then "Escavação Mecanizada em Campo Aberto"
      when 180 then "Carga de Material"
      when 181 then "Execução de Cortes e  Aterros"
      when 182 then "Transportes"
      when 183 then "Locação de Serviços de Terraplenagem e Acompanhamento Topográfico da Obra"
      when 184 then "Demarcação de Quadras e Lotes"
      when 185 then "Sinalização Vertical"
      when 186 then "Sinalização Horizontal"
      when 187 then "Regularização do Subleito"
      when 188 then "Reforço do Sub - Leito"
      when 189 then "Preparo de Materiais em Usina"
      when 190 then "Concreto Betuminoso - Usinagem"
      when 191 then "Sub - Base Estabilizada Granulometricamente"
      when 192 then "Sub - Base com Solo Cimento"
      when 193 then "Base Estabilizada Granulometricamente"
      when 194 then "Base com Solo-Cimento"
      when 195 then "Imprimação"
      when 196 then "Pintura de Ligação"
      when 197 then "Tratamento Superficial"
      when 198 then "Pavimentação com Concreto Betuminoso Pré-misturado a Frio"
      when 199 then "Pavimentação com Concreto Betuminoso Usinado a Quente (CBUQ)"
      when 200 then "Pavimentação com Areia-Asfalto a Quente"
      when 201 then "Pavimentação em Concreto Armado"
      when 202 then "Pavimentação em Paralepípedo ou com Peças Pré-moldadas de Concreto"
      when 203 then "Base de Macadame Hidráulico"
      when 204 then "Sarjetas"
      when 205 then "Meios-Fios e Guias"
      when 206 then "Controle Tecnológico"
      when 207 then "Areia-asfalto - Usinagem"
      when 208 then "Fornencimento de Ligantes Betuminosos"
      when 209 then "Serviços Iniciais"
      when 210 then "Desmontagem/Remoção de Tubos e Conexões"
      when 211 then "Serviços de Proteção e Segurança"
      when 212 then "Fornecimento de Tubos de PVC Junta Elástica, Ponta e Bolsa"
      when 213 then "Fornecimento de Conexões de PVC Junta Elástica"
      when 214 then "Assentamento/Montagem de Tubos e Conexões"
      when 215 then "Fornecimento de Tubos de PVC DEFOFO, Junta Elástica - PN 1MPa"
      when 216 then "Fornecimento de Conexões de PVC DEFOFO, Junta Elástica, PN 1MPa"
      when 217 then "Fornecimento de Tubos de Ferro Fundido"
      when 218 then "Fornecimento de Conexões de Ferro Fundido com Junta Elástica"
      when 219 then "Fornecimento de Conexões de Ferro Fundido com Junta Travada"
      when 220 then "Fornecimento de Conexões de Ferro Fundido com  Junta Mecânica"
      when 221 then "Fornecimento de Conexões de Ferro Fundido com Juntas com Flanges PN 10"
      when 222 then "Fornecimento de Conexões de Ferro Fundido com Juntas com Flanges PN 16"
      when 223 then "Fornecimento de Conexões de Ferro Fundido com Juntas com Flanges PN 25"
      when 224 then "Fornecimento de Peças de Montagem e de Intervenção, em Ferro Fundido"
      when 225 then "Assentamento de Peças de Montagem e de Intervenção, em Ferro Fundido"
      when 226 then "Fornecimento de Tubos em  Aço"
      when 227 then "Fornecimento de Tubos de Polietileno de Alta Densidade (PEAD)"
      when 228 then "Fornecimento de Conexões de Polietileno de Alta Densidade (PEAD)"
      when 229 then "Execução de Caixas para Registros, Ventosas, Descargas e Macro-Medidores"
      when 230 then "Fornecimento de Registros"
      when 231 then "Assentamento de Registros"
      when 232 then "Fornecimento de Válvulas"
      when 233 then "Assentamento de Válvulas"
      when 234 then "Fornecimento de Macro-Medidores, Filtros para Macro-Medidores e Ventosas"
      when 235 then "Assentamento de Macro-Medidores, Filtros para Macro-Medidores e Ventosas"
      when 236 then "Blocos de Ancoragem"
      when 237 then "Chafarizes"
      when 238 then "Fornecimento de Hidrômetros"
      when 239 then "Ligações Prediais de Água"
      when 240 then "Teste Hidrostático e Desinfecção de Redes de Água e Adutoras"
      when 241 then "Cadastro Técnico e Comercial dos Consumidores"
      when 242 then "Transportes de Tubos e Conexões"
      when 243 then "Serviços Diversos"
      when 244 then "Fornecimento de Equipamentos de Medição"
      when 245 then "Assentamento de Equipamentos de Medição"
      when 246 then "Fornecimento de Dosadores e Extintores de Cal"
      when 247 then "Instalação de Dosadores e Extintores de Cal"
      when 248 then "Fornecimento de Misturadores"
      when 249 then "Instalação de Misturadores"
      when 250 then "Fornecimento de Equipamentos de Floculação"
      when 251 then "Instalação de Equipamentos de Floculação"
      when 252 then "Fornecimento de Equipamentos de Decantação"
      when 253 then "Instalação de Equipamentos de Decantação"
      when 254 then "Fornecimento de Materiais para Filtragem"
      when 255 then "Colocação de  Materiais para Filtragem"
      when 256 then "Fornecimento de Equipamentos para Desinfecção"
      when 257 then "Instalação de Equipamentos para Desinfecção"
      when 258 then "Fornecimento de Equipamentos para Estações de Tratamento e Elevatórias de Água"
      when 259 then "Instalação de Equipamentos para Estações de Tratamento e Elevatórias de Água"
      when 260 then "Fornecimento de Bombas e Válvulas de Pé"
      when 261 then "Instalação de Bombas e Válvulas de Pé"
      when 262 then "Serviços Preliminares para Execução de Poços Profundos"
      when 263 then "Perfurações"
      when 264 then "Revestimento e Proteção"
      when 265 then "Montagem"
      when 266 then "Desenvolvimento, ensaio de vazão, entrega do poço"
      when 267 then "Locação e Acompanhamento Topográfico de Redes de Esgotos"
      when 268 then "Lastros, Lajes e Berços"
      when 269 then "Fornecimento de Tubos de PVC Junta Elástica para Redes de Esgotos Sanitários, Ponta e Bolsa"
      when 270 then "Assentamento de Tubos de PVC Junta Elástica para Redes de Esgotos Sanitários, Ponta e Bolsa"
      when 271 then "Fornecimento de Conexões de PVC Junta Elástica para Redes de Esgoto"
      when 272 then "Assentamento de Conexões de PVC Junta Elástica para Redes de Esgotos Sanitários"
      when 273 then "Fornecimento de Tubo de Concreto para Redes de Esgotos Sanitários"
      when 274 then "Assentamento de Tubo de Concreto para Redes de Esgotos Sanitários"
      when 275 then "Poços de Visita para Redes de Esgoto"
      when 276 then "Fornecimento de Tampões para Poços de Visita e Caixas de Inspeção"
      when 277 then "Ligações Prediais de Esgotos"
      when 278 then "Cadastro de Redes Urbanas de Esgotos"
      when 279 then "Fornecimento de Bombas para Estações de Tratamento e Elevatórias de Esgotos"
      when 280 then "Instalação de Bombas em Estações de Tratamento e Elevatórias de Esgotos"
      when 281 then "Fornecimento de Equipamentos para Estações de Tratamento e Elevatórias de Esgotos Sanitários"
      when 282 then "Instalação de Equipamentos em Estações de Tratamento e Elevatórias de Esgotos Sanitários"
      when 283 then "Serviços Preliminares para Execução de Redes de Drenagem"
      when 284 then "Entradas e Saídas D'agua"
      when 285 then "Bueiros Tubulares e Celulares"
      when 286 then "Poços de Visita para Redes de Drenagem"
      when 287 then "Estruturas Complementares"
      when 288 then "Drenos"
      when 289 then "Caixas de Passagem em alvenaria de tijolos maciços"
      when 290 then "Bocas de Lobo"
      when 291 then "Cadastro de Redes de Drenagem"
      when 292 then "Limpeza e Desobstrução de Bueiros"
      when 293 then "Locação da Rede de Irrigação e Acompanhamento Topográfico da Obra"
      when 294 then "Fornecimento de Tubo de PVC PEAD para Redes de Irrigação"
      when 295 then "Assentamernto de Tubo de PVC PEAD para Redes de Irrigação"
      when 296 then "Fornecimento de Tubo de Alumínio, Tipo Engate Rápido, para Redes de Irrigação"
      when 297 then "Assentamento de Tubo de Alumínio, Tipo Engate Rápido, para Redes de Irrigação"
      when 298 then "Fornecimento de Tubos de PVC Engate Rápido"
      when 299 then "Assentamento de Tubos de PVC para Micro-Aspersão"
      when 300 then "Fornecimento de Hidrantes, Aspersores e Acessórios para Irrigação"
      when 301 then "Assentamento de Hidrantes, Aspersores e Acessórios para Irrigação"
      when 302 then "Serviços Preliminares para Execução de Redes de Energia Elétrica e de Iluminação Pública"
      when 303 then "Fornecimento de Materiais para Redes de Energia Elétrica e Iluminação"
      when 304 then "Serviços em Redes de Energia Elétrica e Iluminação"
      when 305 then "Cadastro de Redes de Distribuição de Energia"
      when 306 then "Serviços Preliminares para Execução de Redes de Telefonia"
      when 307 then "Dutos e Sub-Dutos"
      when 308 then "Caixas"
      when 309 then "Cadastro de Redes de Telefonia"
      when 310 then "Gabiões"
      when 311 then "Muros de Arrimo"
      when 312 then "Cortinas de Contenção"
      when 313 then "Enrocamentos"
      when 314 then "Mantas Geotéxteis"
      when 315 then "Concreto e Argamassas Projetados e Injetados"
      when 316 then "Ensecadeiras"
      when 317 then "Escoramentos de Valas, Cavas e Poços"
      when 318 then "Cimbramentos de Grandes Estruturas"
      when 319 then "Bombeamento Direto"
      when 320 then "Equipes de Montagem e Construção"
      when 321 then "Manuseio de Equipamentos, Peças e Conexões"
      when 322 then "Nivelamento e Fixação de Equipamentos, Peças e Conexões"
      when 323 then "Execução de Juntas Flangeadas em Ferro Fundido"
      when 324 then "Execução de Junta Elástica em Ferro Fundido"
      when 325 then "Execução de Junta Mecânica em Ferro Fundido"
      when 326 then "Montagem de Quadros de Comando para Equipamentos"
      when 327 then "Vale Tranporte"
      when 328 then "Alimentação"
      when 329 then "Equipamentos de Proteção Individual (EPI)"
      when 330 then "Procedimentos para Elaboração"
      when 331 then "Conversão InfoWOrca"
      when 333 then "Estações Elevatórias e Estações de Tratamento de Esgotos"
      when 334 then "Pessoal Técnico e Administrativo para Elaboração de Projetos e Gerenciamento de Obras"
      when 335 then "Remoção de tubos/conexões em redes coletoras de esgoto"
      when 336 then "Esquadrias de PVC"
      when 337 then "Novo Item"
      when 338 then "Restauro"
      when 339 then "Ferragens"
      when 340 then "Reparo, Proteção e Reforço de Estrutura de Concreto Armado"
      when 341 then "Junta de dilatação"
      when 342 then "Novo Item"
    else
      self
    end
  end

  Alph = ("a".."z").to_a
  def alph
    s, q = "", self
    (q, r = (q - 1).divmod(26)); s.prepend(Alph[r]) until q.zero?
    s
  end

  Alpha26 = ("a".."z").to_a
  def to_s26
    return "" if self < 1
    s, q = "", self
    loop do
      q, r = (q - 1).divmod(26)
      s.prepend(Alpha26[r]) 
      break if q.zero?
    end
    s
  end

  def trocar_ponto_por_virgula(n_casas_decimais = nil)
    "#{self},0"
  end

  def atalhos_to_nome
    case self
      when 48 then "0"
      when 49 then "1"
      when 50 then "2"
      when 51 then "3"
      when 52 then "4"
      when 53 then "5"
      when 54 then "6"
      when 55 then "7"
      when 56 then "8"
      when 57 then "9"
      when 65 then "a"
      when 66 then "b"
      when 67 then "c"
      when 68 then "d"
      when 69 then "e"
      when 70 then "f"
      when 71 then "g"
      when 72 then "h"
      when 73 then "i"
      when 74 then "j"
      when 75 then "k"
      when 76 then "l"
      when 77 then "m"
      when 78 then "n"
      when 79 then "o"
      when 80 then "p"
      when 81 then "q"
      when 82 then "r"
      when 83 then "s"
      when 84 then "t"
      when 85 then "u"
      when 86 then "v"
      when 87 then "w"
      when 88 then "x"
      when 89 then "y"
      when 90 then "z"
      when 96 then "Teclado Numérico - 0"
      when 97 then "Teclado Numérico - 1"
      when 98 then "Teclado Numérico - 2"
      when 99 then "Teclado Numérico - 3"
      when 100 then "Teclado Numérico - 4"
      when 101 then "Teclado Numérico - 5"
      when 102 then "Teclado Numérico - 6"
      when 103 then "Teclado Numérico - 7"
      when 104 then "Teclado Numérico - 8"
      when 105 then "Teclado Numérico - 9"
      when 106 then "Teclado Numérico - *"
      when 107 then "Teclado Numérico - +"
      when 109 then "Teclado Numérico - -"
      when 110 then "Teclado Numérico - ."
      when 111 then "Teclado Numérico - /"
      when 186 then ";"
      when 187 then "="
      when 188 then ","
      when 189 then "-"
      when 190 then "."
      when 191 then "/"
      when 219 then "["
      when 220 then "\\"
      when 221 then "]"
      when 222 then "'"
    else
      ""
    end
  end
end